inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/*'
    - 'bin/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# TEMP: private and def foo() are at the same indentation level
# This should NOT cause an offense but it does. ¯\_(ツ)_/¯
# https://rubocop.readthedocs.io/en/latest/cops_layout/
Layout/IndentationWidth:
  Enabled: false

Metrics/BlockLength:
  Max: 153

Metrics/BlockNesting:
  Max: 4

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

# README: the `begin` in BadRequestRescue seems to be required
Style/RedundantBegin:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# TEMP: Nokogiri’s use of `open` from `open-uri` is being
# confused as Kernel#open by Rubocop
Security/Open:
  Enabled: false

# Allow: end # if foo?
Style/CommentedKeyword:
  Exclude:
    - 'lib/tasks/scraper.rake'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
