default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: illinois_sbe_donors_development

test:
  <<: *default
  host: localhost
  database: illinois_sbe_donors_test

production:
  <<: *default
  database: illinois_sbe_donors_production
  username: illinois_sbe_donors
  password: <%= ENV['ILLINOIS_SBE_DONORS_DATABASE_PASSWORD'] %>